package com.courtai.advocate.dto;

import com.courtai.common.enums.CasePriority;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;

/**
 * Request DTO for filing a new case through the Advocate Portal.
 * The case number is auto-generated by the system — advocates do not set it.
 */
@Getter
@Setter
public class CreateCaseRequest {

    @NotBlank(message = "Case title is required")
    @Size(max = 500, message = "Case title must not exceed 500 characters")
    private String caseTitle;

    @Size(max = 5000, message = "Description must not exceed 5000 characters")
    private String caseDescription;

    @NotNull(message = "Case type is required")
    private String caseType;

    @NotBlank(message = "Petitioner name is required")
    @Size(max = 200)
    private String petitionerName;

    @NotBlank(message = "Respondent name is required")
    @Size(max = 200)
    private String respondentName;

    private LocalDate filingDate;

    /** UUID of the court where the case is being filed. */
    private String courtUuid;

    /** UUID of the case category. */
    private String caseCategoryUuid;

    /** UUID of the respondent's advocate (if known at filing time). */
    private String respondentAdvocateUuid;

    @Size(max = 200)
    private String policeStation;

    @Size(max = 500)
    private String actSection;

    private CasePriority priority;

    // --- Added for 17-step Wizard Flow (Steps 1 & 2) ---

    // Step 1: Where to File
    private String state;
    private String district;
    private String courtEstablishment;
    private String bench;
    private String courtHall;
    private String caseNature; // Civil / Criminal
    private String filingMode; // e.g. Fresh
    private String signingMethod; // Aadhaar eSign / DSC
    private String language;

    // Step 2: Case Information (some overlap with existing fields)
    private String causeTitle;
    private String subject;
    private String natureOfSuit;
    private String reliefSought;
    private String causeOfAction;
    private LocalDate dateOfCauseAction;
}
