package com.courtai.judge.dto;

import lombok.Builder;
import lombok.Getter;

import java.time.LocalDateTime;

/**
 * Read-only AI analysis result for the judge.
 * All scores are on a 0–100 scale. Higher = more urgent/reliable.
 */
@Getter
@Builder
public class JudgeAiAnalysisResponse {

    private String uuid;
    private String caseUuid;

    /** AI-computed urgency score (0–100). Higher = more time-critical. */
    private Double urgencyScore;

    /** Impact of further delay on case justice (0–100). */
    private Double delayImpactScore;

    /** AI-computed priority score (from CaseFile). */
    private Double priorityScore;

    /** Trustworthiness/reliability score of submitted documents (0–100). */
    private Double trustScore;

    /** Confidence level of the AI model in its own analysis (0–100). */
    private Double confidenceScore;

    /** Human-readable recommendation generated by the AI model. */
    private String recommendation;

    /**
     * Explainable AI (XAI) factors as a JSON string.
     * Extracted from the raw AI response for transparency.
     */
    private String explainableAiFactors;

    /** Version identifier of the AI model that produced this analysis. */
    private String modelVersion;

    /** Timestamp when the AI model generated this analysis. */
    private LocalDateTime generatedAt;

    /** Processing time in milliseconds (parsed from raw response). */
    private Long processingTimeMs;
}
