package com.courtai.ai.entity;

import com.courtai.casefile.entity.CaseFile;
import com.courtai.common.entity.BaseEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Stores the AI analysis result for a judicial case.
 *
 * <p><strong>Placeholder entity — no business logic implemented.</strong>
 * This entity is a data sink for results produced by the FastAPI AI service.
 * It will be populated asynchronously after a case enters the AI analysis queue.</p>
 *
 * <p>Scores are on a 0–100 scale. Higher values indicate greater urgency or risk.</p>
 */
@Entity
@Table(
        name = "case_analysis",
        indexes = {
                @Index(name = "idx_analysis_case_id",    columnList = "case_id"),
                @Index(name = "idx_analysis_is_deleted", columnList = "is_deleted")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CaseAnalysis extends BaseEntity {

    /** The case this analysis result belongs to. */
    @NotNull
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "case_id", nullable = false, unique = true)
    private CaseFile caseFile;

    /** AI-computed urgency score (0–100). Higher = more time-critical. */
    @Column(name = "urgency_score")
    private Double urgencyScore;

    /** Score representing the impact of further delay on case justice (0–100). */
    @Column(name = "delay_impact_score")
    private Double delayImpactScore;

    /** Trustworthiness/reliability score of the submitted documents (0–100). */
    @Column(name = "trust_score")
    private Double trustScore;

    /** Confidence level of the AI model in its own analysis (0–100). */
    @Column(name = "confidence_score")
    private Double confidenceScore;

    /** Human-readable recommendation generated by the AI model. */
    @Column(name = "recommendation", columnDefinition = "TEXT")
    private String recommendation;

    /** Version identifier of the AI model that produced this analysis. */
    @Column(name = "model_version", length = 50)
    private String modelVersion;

    /** Timestamp when the AI model generated this analysis. */
    @Column(name = "generated_at")
    private LocalDateTime generatedAt;

    /** Full JSON response from the FastAPI AI service for debugging. */
    @Column(name = "raw_response", columnDefinition = "TEXT")
    private String rawResponse;
}
