// ─── Shared Hooks Barrel — Phase F3 ──────────────────────────────────────────
export { useDebounce, useDebouncedCallback } from './useDebounce'
export { usePagination }                      from './usePagination'
export { useSorting }                         from './useSorting'
export { useFiltering }                       from './useFiltering'
export { useSearch }                          from './useSearch'
export { useSelection }                       from './useSelection'
export { useInfiniteScroll }                  from './useInfiniteScroll'
export { useVirtualization }                  from './useVirtualization'
export { useClipboard }                       from './useClipboard'
export { useDownload }                        from './useDownload'
export { useUpload }                          from './useUpload'
export { useResize, useDragResize }           from './useResize'
export { useFullscreen }                      from './useFullscreen'

export type { UseSelectionReturn }            from './useSelection'
export type { UseSearchOptions }              from './useSearch'
export type { UseInfiniteScrollOptions }      from './useInfiniteScroll'
export type { UseVirtualizationOptions }      from './useVirtualization'
export type { Size }                          from './useResize'
