package com.courtai.ai.workflow.service;

import com.courtai.ai.workflow.model.Workflow;

public interface ResearchTrackingService {
    
    /**
     * Hooks to record workflow execution metrics (latency, retry count) for the research dataset.
     */
    void trackWorkflowExecution(Workflow workflow);
    
    /**
     * Hooks to track if a judge modified or rejected an AI recommendation generated by this workflow.
     */
    void trackJudicialFeedback(String workflowUuid, boolean accepted, boolean modified, String feedback);
}
